export enum ACTION_TYPE {
    GET_CITY = 'WEATHER/GET_NAME',
    SET_ERROR = 'WEATHER/SET_ERROR',
    UPDATE_DATA = 'WEATHER/UPDATE_DATA',
    DELETE_DATA = 'WEATHER/DELETE_DATA',
    SHOW_MODAL = 'WEATHER/SHOW_MODAL',
}